[package]
name = "tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
domain.workspace = true
ratatui.workspace = true
crossterm.workspace = true
vim-line = "7.7"
unicode-width.workspace = true
unicode-segmentation.workspace = true
emojis.workspace = true

[lints]
workspace = true
