[package]
name = "tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
domain.workspace = true
ratatui.workspace = true
crossterm.workspace = true
vim-line = "7.7"
unicode-width.workspace = true
unicode-segmentation.workspace = true
unicode-bidi.workspace = true
emojis.workspace = true
image-webp.workspace = true
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "wrap_rows"
harness = false

[lints]
workspace = true
